version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: yotas
      POSTGRES_PASSWORD: yotas
      POSTGRES_USER: yotas
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  start-postgres:
    depends_on:
      - postgres
    image: golang:buster
    command: ["/start-postgres/dev/scripts/wait-for-it/wait-for-it.sh", "postgres:5432", "--", "/start-postgres/dev/setup-postgres/setup-postgres.sh"]
    volumes:
      - .:/start-postgres

  api:
    depends_on:
      - start-postgres
    image: golang:buster
    command: ["/bin/bash", "-c", "cd /api/ && make run"]
    env_file:
      - ./dev/setup-postgres/env
    volumes:
      - .:/api

    ports:
      - 9999:9999
