name: Run end to end tests

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/run-end2end-test.yaml

jobs:
  e2etest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run Backend Tests
        working-directory: ./backend
        run: make docker-e2etest
